# Generated by Django 4.2.7 on 2024-02-03 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain uppercase and lowecase letters, min 8 symbols.', regex='[A-Za-z0-9@#$%^&+=s]{8,}')]),
        ),
    ]
