# Generated by Django 4.2.7 on 2024-02-23 09:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_usermodel_avatar_avatarmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number, example: 0664172591 ', regex='^\\(0\\d{9})$')]),
        ),
    ]
