# Generated by Django 4.2.7 on 2024-02-23 10:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Password must contain uppercase and lowercase letters, min 8 characters.', regex='^(?=.*[a-z])(?=.*[A-Z]).{8,}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number, example: 0664172591 ', regex='^0(|50|63|66|67|68|73|91|92|93|94|95|96|97|98|99)\\d{7}$')]),
        ),
    ]
