# Generated by Django 4.2.7 on 2024-02-23 14:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_usermodel_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number, example: 0664172591 ', regex='^(050|063|066|067|068|073|091|092|093|094|095|096|097|098|099)\\d{7}$`')]),
        ),
    ]
