# Generated by Django 4.2.7 on 2024-02-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_itemmodel_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
