# Generated by Django 4.2.7 on 2024-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0005_itemmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='image',
            field=models.CharField(max_length=120),
        ),
    ]
