# Generated by Django 4.2.7 on 2024-02-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0009_imageitemmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitemmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
