# Generated by Django 4.2.7 on 2024-02-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0010_alter_imageitemmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitemmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
