# Generated by Django 4.2.7 on 2023-12-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentmodel',
            name='general_number',
            field=models.IntegerField(unique=True),
        ),
    ]
