# Generated by Django 4.2.7 on 2023-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverymodel',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('recieved', 'Recieved'), ('declined', 'Declined')], default='in progress', max_length=11),
        ),
    ]
