# Generated by Django 4.2.7 on 2023-12-01 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0003_alter_itemmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverymodel',
            name='reciever',
        ),
        migrations.AddField(
            model_name='deliverymodel',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receiving', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('received', 'Recieved'), ('declined', 'Declined')], default='in progress', max_length=11),
        ),
    ]
