# Generated by Django 4.2.7 on 2023-12-04 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('deliveries', '0004_remove_deliverymodel_reciever_deliverymodel_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymodel',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='departments.departmentmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverymodel',
            name='status',
            field=models.CharField(choices=[('in progress', 'In Progress'), ('ready', 'Ready'), ('received', 'Recieved'), ('declined', 'Declined')], default='in progress', max_length=11),
        ),
    ]
