# Generated by Django 4.2.7 on 2023-12-16 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_number', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('region', models.CharField(choices=[('Kyiv', 'Kyiv'), ('Chernihiv', 'Chernihiv'), ('Sevastopol', 'Sevastopol'), ('Cherkasy', 'Cherkasy'), ('Khmelnytskyi', 'Khmelnytskyi'), ('Chernivtsi', 'Chernivtsi'), ('Kherson', 'Kherson'), ('Kharkiv', 'Kharkiv'), ('Ternopil', 'Ternopil'), ('Vinnitsya', 'Vinnitsya'), ('Sumy', 'Sumy'), ('Rivne', 'Rivne'), ('Poltava', 'Poltava'), ('Odesa', 'Odesa'), ('Lviv', 'Lviv'), ('Luhansk', 'Luhansk'), ('Kirovohrad', 'Kirovohrad'), ('Ivano_Frankivsk', 'Ivano Frankivsk'), ('Zaporizhya', 'Zaporizhya'), ('Zhytomyr', 'Zhytomyr'), ('Donetsk', 'Donetsk'), ('Crimea', 'Crimea'), ('Dnipro', 'Dnipro'), ('Volin', 'Volin')], max_length=15)),
                ('status', models.BooleanField(default=True)),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(1000)])),
                ('staff_count', models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(30)])),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
    ]
