# Generated by Django 4.2.7 on 2024-02-29 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_alter_departmentmodel_general_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentmodel',
            name='region',
        ),
        migrations.AlterField(
            model_name='departmentmodel',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
